db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: npm start
  volumes:
    - .:/crawlernodeapi
  ports:
    - "5000:5000"
  links:
    - db